/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options accepted by `capture`. */
export interface CaptureOptions {
  /** Page to capture. */
  url: string
  /** Where PNGs are written. Defaults to `./proofsheet-out`. */
  outDir?: string
  /** Explicit device ids. Takes precedence over `store`. */
  devices?: Array<string>
  /** Capture every preset for `apple`, `play` or `web`. */
  store?: string
  /** Determinism seed. Defaults to 42. */
  seed?: number
  /** Locale override, e.g. `en-US`. */
  locale?: string
  /** Timezone override, e.g. `UTC`. */
  timezone?: string
  /** Path to a Chromium binary. Defaults to discovery. */
  browser?: string
  /** Stop at the first failure. */
  failFast?: boolean
  /** Path to a preset JSON file, replacing the built-in table. */
  presets?: string
}
/** What the page reported about itself during a capture. */
export interface JsEnvironment {
  innerWidth: number
  innerHeight: number
  devicePixelRatio: number
  touchPoints: number
  /**
   * False means the page overrode the layout viewport, which usually means
   * content negotiation served the wrong layout at the right pixel count.
   */
  viewportHonoured: boolean
}
/** One image, as JavaScript sees it. */
export interface JsCapture {
  /** Pixel width the store requires. */
  expectedWidth: number
  expectedHeight: number
  /** Pixel width actually produced. */
  actualWidth: number
  actualHeight: number
  /** Content address of the PNG bytes. */
  sha256: string
  bytes: number
  /** True when actual matches expected exactly. */
  exact: boolean
  /**
   * What the page saw. Assert on this as well as the dimensions: a capture
   * can be exactly the right size and still show the wrong layout.
   */
  environment?: JsEnvironment
}
/** One device's result, successful or not. */
export interface JsDeviceResult {
  deviceId: string
  /** `exact`, `off-size` or `failed`. */
  outcome: string
  elapsedMs: number
  capture?: JsCapture
  /** Present only when the capture failed. */
  error?: string
  /** Where the PNG was written. */
  path?: string
}
/** The result of a capture run. */
export interface ProofsheetReport {
  /** Version of the native core that produced this. */
  proofsheet: string
  url: string
  seed: number
  locale: string
  exact: number
  offSize: number
  failed: number
  elapsedMs: number
  /**
   * True only when at least one capture happened and none went wrong.
   * Callers should branch on this rather than on `failed === 0`, which is
   * also true for a run that captured nothing at all.
   */
  ok: boolean
  results: Array<JsDeviceResult>
}
/**
 * Capture screenshots at exact store dimensions.
 *
 * Resolves with a [`ProofsheetReport`]. Branch on `report.ok`, not on
 * `report.failed === 0` — the latter is also true when nothing was captured.
 */
export declare function capture(options: CaptureOptions): Promise<unknown>
/** List device presets, optionally filtered to one store. */
export declare function devices(store?: string | undefined | null, presets?: string | undefined | null): any
/** Locate the browser proofsheet would use, or throw explaining why it cannot. */
export declare function findBrowser(): string
/**
 * The native core version. Kept in lockstep with the npm package version by
 * a CI check, because a binding reporting a different version than the
 * package it ships in makes every bug report ambiguous.
 */
export declare function version(): string
